name: LimnoTech Image Test
on: 
  push:
    branches:
      - "s3-edr"
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the pygeoapi-base Docker Image. 
run: |
       docker build . --tag ghcr.io/LimnoTech/pygeoapi-base:latest
       docker run ghcr.io/LimnoTech/pygeoapi-base:latest
       docker push ghcr.io/LimnoTech/pygeoapi-base:latest